### ISSUE TITLE
Add models to docker

### ISSUE THREAD

**Issue by Marceau-h** [aymara/lima#158]
**Describe the bug**
Hi,
I'm unable to use lima_models.py to add models to the docker image
I've tried restarting the docker to relaunch the limaserver after the dowloads but it didn't wort either, maybe it's linked to persistent storage but I couldn't make it work

**To Reproduce**
1. Access docker container's console
2. Download a model with `lima_models.py -l XXX`
3. The model downloads fine
4. Try to use the model with `http://ip:port/?lang=XXX&pipeline=deep` and the payload

**Expected behavior**
The server should return the processed verion of the text

**Screenshots**
![image](https://user-images.githubusercontent.com/106751184/231703807-f9d4c66f-9478-48fe-9afd-aa46e52c845f.png)
![image](https://user-images.githubusercontent.com/106751184/231703860-6cc1a328-5e0f-4925-8488-f096c01dcfd0.png)

**Desktop (please complete the following information):**
 - OS: fedora
 - Browser chrome
 - Version 112
 - Also tried with python's module http.client 

**Additional context**
I also tried downloading the language `zho-simp` which didn't work. It seems to be related to the dash inside the name ? Should I open another issue or anything ?

**Comment by kleag** [comment]
Try to init Lima with the language "ud-spa" instead of spa.
But be careful, all data downloaded from a shell inside a container will be lost when the container stops. To keep downloaded models, you will have to mount a volume in your container and then to use the `-d` switch of `lima_models.py` to download into the mounted volume. Finally, you will have to set environment variables when launching your container for Lima to use the resources in your volume (`LIMA_CONF` and `LIMA_RESOURCES`).

**Comment by Marceau-h** [comment]
Thanks for your help, the "ud-spa" finally worked !

I didn't managed to make it work with the envtionnement variables, so I mounted the default paths `/root/.local/share//lima/resources/` and `/usr/share/apps/lima/resources` and now it works just fine.


I still have a small issue, i can't install the `zho-simp` model. It maybe seems to be caused by the dash in the language code and the split that occurs on the dash? Should I open another ticket? 

Thanks again for your help,
Marceau
