### ISSUE TITLE
Modex classes with entity types do not work

### ISSUE THREAD

**Issue by kleag** [aymara/lima#68]

**Comment by kleag** [comment]
The rule below does not match:
@ClassA=(<A>,<B>)
@ClassB=(<C>,<D>)
vu::(la|le) @ClassA en @ClassB:TYPE:

While this one does with the same text:
vu::la <A> en <C>:TYPE:

It seems that classes with entity types do not work as expected.

**Comment by romaricb** [comment]
Since the work on the optimization of the use of gazetteers (by @mesnard ), the classes only accept words (single terms or multi-terms).

Workaround here is :

- directly use `(<A>|<B>)` in the rule
- if the size of the list is too important, use sub-automatons:
```
define subautomaton ClassA {
  pattern=(<A>|<B>)
}
define subautomaton ClassB {
  pattern=(<C>|<D>)
}

vu::(la|le) %ClassA en %ClassB:TYPE:
```

Another possibility would be to have a conditional handling of classes during compilation, depending if they contain entities/lemmas/pos or just words). To be discussed.

**Comment by romaricb** [comment]
Corrected.
(commit 12647e4c4c3f)
